# Copyright (c) 2026 Yuichi Ito (yuichi@yuichi.com)
#
# This software is licensed under the Apache License, Version 2.0.
# For more information, please visit: https://github.com/yuichi110/drawlib
#
# This software is provided "as is", without warranty of any kind,
# express or implied, including but not limited to the warranties of
# merchantability, fitness for a particular purpose and noninfringement.

"""Package for core drawing action modules."""

from drawlib._core.l2_types_._font import (
    Font,
    TypeFont,
)
from drawlib._core.l2_types_._geometry import (
    Bezier2,
    Bezier3,
    Coordinate,
    Coordinates,
    PathPoint,
    PathPoints,
    TypeBezier2,
    TypeBezier3,
    TypeCoordinate,
    TypeCoordinates,
    TypePathPoint,
    TypePathPoints,
)
from drawlib._core.l2_types_._image import (
    ImageFormat,
    ImageQuality,
    ImageResample,
    ImageZoom,
    TypeImageFormat,
    TypeImageQuality,
    TypeImageResample,
    TypeImageZoom,
)
from drawlib._core.l2_types_._path import (
    FilePath,
    TypeFilePath,
)
from drawlib._core.l2_types_._primitive import (
    NegFloat,
    NegInt,
    NumVertex,
    PosFloat,
    PosInt,
    TypeBool,
    TypeFloat,
    TypeInt,
    TypeNegFloat,
    TypeNegInt,
    TypeNumVertex,
    TypePosFloat,
    TypePosInt,
    TypeStr,
)
from drawlib._core.l2_types_._style import (
    Alpha,
    Angle,
    Angle90,
    ArrowHead,
    Bend,
    Color,
    ColorRGB,
    ColorRGBA,
    HAlign,
    IconStyle,
    LineStyle,
    Size,
    TailEdge,
    TypeAlpha,
    TypeAngle,
    TypeAngle90,
    TypeArrowHead,
    TypeBend,
    TypeColor,
    TypeColorRGB,
    TypeColorRGBA,
    TypeHAlign,
    TypeIconStyle,
    TypeLineStyle,
    TypeSize,
    TypeTailEdge,
    TypeVAlign,
    VAlign,
)

__all__ = [
    # Modern types
    "Alpha",
    "Angle",
    "Angle90",
    "ArrowHead",
    "Bend",
    "Bezier2",
    "Bezier3",
    "Color",
    "ColorRGB",
    "ColorRGBA",
    "Coordinate",
    "Coordinates",
    "FilePath",
    "Font",
    "HAlign",
    "IconStyle",
    "ImageFormat",
    "ImageQuality",
    "ImageResample",
    "ImageZoom",
    "LineStyle",
    "NegFloat",
    "NegInt",
    "NumVertex",
    "PathPoint",
    "PathPoints",
    "PosFloat",
    "PosInt",
    "Size",
    "TailEdge",
    "VAlign",
    # Backward compatibility aliases
    "TypeAlpha",
    "TypeAngle",
    "TypeAngle90",
    "TypeArrowHead",
    "TypeBend",
    "TypeBezier2",
    "TypeBezier3",
    "TypeBool",
    "TypeColor",
    "TypeColorRGB",
    "TypeColorRGBA",
    "TypeCoordinate",
    "TypeCoordinates",
    "TypeFilePath",
    "TypeFloat",
    "TypeFont",
    "TypeHAlign",
    "TypeIconStyle",
    "TypeImageFormat",
    "TypeImageQuality",
    "TypeImageResample",
    "TypeImageZoom",
    "TypeInt",
    "TypeLineStyle",
    "TypeNegFloat",
    "TypeNegInt",
    "TypeNumVertex",
    "TypePathPoint",
    "TypePathPoints",
    "TypePosFloat",
    "TypePosInt",
    "TypeSize",
    "TypeStr",
    "TypeTailEdge",
    "TypeVAlign",
]
