version: '3'

dotenv: ['.env']

includes:
  check: ./tasks/check.yml
  docker: ./tasks/docker.yml
  gen: ./tasks/gen.yml
  pypi: ./tasks/pypi.yml
  pypi-test: ./tasks/pypi_test.yml
  pyproject: ./tasks/pyproject.yml
  setup: ./tasks/setup.yml
  utest: ./tasks/unit_tests/Taskfile.yml
  dependency: ./tasks/dependency.yml
  
tasks:
  default:
    desc: Print available tasks
    cmds:
      - task --list
    silent: true
