"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional

"""Validate function arguments data."""
def validate_canvas_args(args: Dict[str, Any]) -> None:
    """Validate configuration arguments.

    Args:
        args (Dict[str, Any]): Dictionary containing configuration arguments.

    Raises:
        ValueError: If any argument fails validation.

    """
    ...

def validate_icon_args(args: Dict[str, Any]) -> None:
    """Validate icon drawing arguments.

    Args:
        args (Dict[str, Any]): Dictionary containing icon drawing arguments.

    Raises:
        ValueError: If any argument fails validation.
    """
    ...

def validate_image_args(args: Dict[str, Any]) -> None:
    """Validate image drawing arguments.

    Args:
        args (Dict[str, Any]): Dictionary containing image drawing arguments.

    Raises:
        ValueError: If any argument fails validation.
    """
    ...

def validate_line_args(args: Dict[str, Any]) -> None:
    """Validate line drawing arguments.

    Args:
        args (Dict[str, Any]): Dictionary containing line drawing arguments.

    Raises:
        ValueError: If any argument fails validation.
    """
    ...

def validate_shape_args(args: Dict[str, Any], argnames_accept_none: Optional[List[str]] = ...) -> None:
    """Validate shape drawing arguments.

    Args:
        args (Dict[str, Any]): Dictionary containing shape drawing arguments.
        argnames_accept_none (List[str], optional): List of argument names that can accept None as a value.

    Raises:
        ValueError: If any argument fails validation.
    """
    ...

def validate_text_args(args: Dict[str, Any]) -> None:
    """Validate text drawing arguments.

    Args:
        args (Dict[str, Any]): Dictionary containing text drawing arguments.

    Raises:
        ValueError: If any argument fails validation.
    """
    ...

