"""
This type stub file was generated by pyright.
"""

from typing import Literal

"""Validate image data."""
def validate_style(arg_name: str, value: Literal["thin", "light", "regular", "bold", "fill"]) -> None:
    """Validate style data.

    Args:
        arg_name (str): Name of the argument or attribute being validated.
        value (str): Value to validate as string data.

    Raises:
        ValueError: If value is not one of ["thin", "light", "regular", "bold", "fill"].

    """
    ...

