"""
This type stub file was generated by pyright.
"""

from typing import Union
from PIL.Image import Image
from drawlib.v0_1.private.core.dimage import Dimage

"""Validate image data."""
def validate_image(arg_name: str, value: Union[str, Image, Dimage]) -> None:
    """Validate image data.

    Args:
        arg_name (str): Name of the argument or attribute being validated.
        value (Union[str, PIL.Image.Image, drawlib.v0_1.private.core.dimage.Dimage]): Value to validate as image data.

    Raises:
        ValueError: If value is not a string, PIL.Image.Image object, or Dimage object.
    """
    ...

