"""
This type stub file was generated by pyright.
"""

from typing import Union

"""Validate shape data."""
def validate_num_vertex(arg_name: str, value: int) -> None:
    """Validate number of vertices for a shape.

    Args:
        arg_name (str): Name of the argument or attribute being validated.
        value (int): Number of vertices to validate.

    Raises:
        ValueError: If value is not an integer greater than or equal to 3.
    """
    ...

def validate_r(arg_name: str, value: Union[int, float]) -> None:
    """Validate radius value for a shape.

    Args:
        arg_name (str): Name of the argument or attribute being validated.
        value (Union[int, float]): Radius value to validate.

    Raises:
        ValueError: If value is not a non-negative integer or float.
    """
    ...

def validate_head_style(arg_name: str, value: str) -> None:
    """Validate head style for a shape.

    Args:
        arg_name (str): Name of the argument or attribute being validated.
        value (str): Head style value to validate.

    Raises:
        ValueError: If value is not one of ["->", "<-", "<->"].
    """
    ...

