"""
This type stub file was generated by pyright.
"""

"""Validate smart art data."""
def validate_tail_edge(name: str, value: str) -> None:
    """Validate tail edge for smart art.

    Args:
        name (str): Name of the argument or attribute being validated.
        value (str): Tail edge value to validate.

    Raises:
        ValueError: If value is not one of ["left", "top", "right", "bottom"].
    """
    ...

