"""
This type stub file was generated by pyright.
"""

from drawlib.v0_1.private.core.model import IconStyle, ImageStyle, LineStyle, ShapeStyle, ShapeTextStyle, TextStyle

"""Validate style data."""
def validate_iconstyle(name: str, value: IconStyle) -> None:
    """Validate icon style.

    Args:
        name (str): Name of the argument or attribute being validated.
        value (IconStyle): IconStyle object to validate.

    Raises:
        ValueError: If value is not an instance of IconStyle.
    """
    ...

def validate_imagestyle(name: str, value: ImageStyle) -> None:
    """Validate image style.

    Args:
        name (str): Name of the argument or attribute being validated.
        value (ImageStyle): ImageStyle object to validate.

    Raises:
        ValueError: If value is not an instance of ImageStyle.
    """
    ...

def validate_linestyle(name: str, value: LineStyle) -> None:
    """Validate line style.

    Args:
        name (str): Name of the argument or attribute being validated.
        value (LineStyle): LineStyle object to validate.

    Raises:
        ValueError: If value is not an instance of LineStyle.
    """
    ...

def validate_shapestyle(name: str, value: ShapeStyle) -> None:
    """Validate shape style.

    Args:
        name (str): Name of the argument or attribute being validated.
        value (ShapeStyle): ShapeStyle object to validate.

    Raises:
        ValueError: If value is not an instance of ShapeStyle.
    """
    ...

def validate_shapetextstyle(name: str, value: ShapeTextStyle) -> None:
    """Validate shape text style.

    Args:
        name (str): Name of the argument or attribute being validated.
        value (ShapeTextStyle): ShapeTextStyle object to validate.

    Raises:
        ValueError: If value is not an instance of ShapeTextStyle.
    """
    ...

def validate_textstyle(name: str, value: TextStyle) -> None:
    """Validate text style.

    Args:
        name (str): Name of the argument or attribute being validated.
        value (TextStyle): TextStyle object to validate.

    Raises:
        ValueError: If value is not an instance of TextStyle.
    """
    ...

