"""
This type stub file was generated by pyright.
"""

from typing import Union
from drawlib.v0_1.private.core.fonts import FontBase, FontFile

"""Validate text data."""
def validate_font(name: str, value: Union[FontBase, FontFile]) -> None:
    """Validate font.

    Args:
        name (str): Name of the argument or attribute being validated.
        value (Union[FontBase, FontFile]): Font object to validate.

    Raises:
        ValueError: If value is not an instance of FontBase or FontFile.

    """
    ...

