"""
This type stub file was generated by pyright.
"""

import typing
import drawlib.v0_1.private.util
from drawlib.v0_1.private.core.model import IconStyle

"""icon() implementation module."""
@drawlib.v0_1.private.util.error_handler
def icon(xy: typing.Tuple[float, float], width: float, code: str, file: str, angle: typing.Union[int, float] = ..., style: typing.Union[IconStyle, str, None] = ...) -> None:
    """Draw an icon from the provided icon font.

    Args:
        xy (Tuple[float, float]): The (x, y) coordinates where the icon will be drawn.
                                   Default alignment is left and bottom if angle is not specified,
                                   center if specified.
        width (float): The width of the icon. The icon might have transparent space.
        code (str): The code point of the icon to be drawn.
        file (str): The path to the font file.
        angle (Union[int, float], optional): The rotation angle of the icon,
                                             ranging from 0.0 to 360.0. Defaults to 0.0.
        style (Union[IconStyle, str, None], optional): The style of the icon, including alignment
                                                       and other properties. Defaults to None.

    Returns:
        None

    """
    ...

