# Copyright (c) 2026 Yuichi Ito (yuichi@yuichi.com)
#
# This software is licensed under the Apache License, Version 2.0.
# For more information, please visit: https://github.com/yuichi110/drawlib
#
# This software is provided "as is", without warranty of any kind,
# express or implied, including but not limited to the warranties of
# merchantability, fitness for a particular purpose and noninfringement.

"""Drawlib Python source code generator from computed GraphLayout geometry."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from drawlib._graph._common._models import (
        ClusterLayout,
        EdgeLayout,
        GraphLayout,
        NodeLayout,
    )


def _format_header_code(width: float, height: float) -> list[str]:
    """Format imports and canvas setup."""
    return [
        "# Generated by Drawlib Graph Engine",
        "from drawlib.canvas import save, setup",
        "from drawlib.lines import line, lines",
        "from drawlib.shapes import circle, rectangle",
        "from drawlib.styles import Colors, Styles",
        "from drawlib.text import text",
        "",
        f"setup(width={width:.1f}, height={height:.1f})",
    ]


def _format_clusters_code(clusters: dict[str, ClusterLayout]) -> list[str]:
    """Format clusters/boundary boxes section."""
    if not clusters:
        return []
    lines: list[str] = [
        "",
        "# " + "=" * 77,
        "# 1. Clusters & Boundaries (Z-Order Layer 1)",
        "# " + "=" * 77,
    ]
    for c in clusters.values():
        if c.shape == "circle":
            r = c.width / 2.0
            lines.append(
                f"circle(({c.cx:.1f}, {c.cy:.1f}), radius={r:.1f}, "
                "style=Styles.MutedDashed)"
            )
            if c.label:
                lines.append(f'text(({c.cx:.1f}, {c.top - 2.0:.1f}), "{c.label}", style=Styles.DarkBold)')
        else:
            lines.append(
                f"rectangle(({c.cx:.1f}, {c.cy:.1f}), width={c.width:.1f}, height={c.height:.1f}, "
                "style=Styles.MutedDashed)"
            )
            if c.label:
                tx = round(c.left + 2.5, 1)
                ty = round(c.top - 2.0, 1)
                lines.append(f'text(({tx:.1f}, {ty:.1f}), "{c.label}", style=Styles.DarkBold)')
    return lines


def _format_edges_code(edges: list[EdgeLayout]) -> list[str]:
    """Format connections and edges section."""
    if not edges:
        return []
    lines: list[str] = [
        "",
        "# " + "=" * 77,
        "# 2. Connections & Edges (Z-Order Layer 2)",
        "# " + "=" * 77,
    ]
    for edge in edges:
        pts = edge.points
        arrow = f'arrow_head="{edge.arrow_head}"'
        pts_str = ", ".join(f"({p[0]:.1f}, {p[1]:.1f})" for p in pts)
        if len(pts) == 2:
            lines.append(
                f"line(({pts[0][0]:.1f}, {pts[0][1]:.1f}), ({pts[1][0]:.1f}, {pts[1][1]:.1f}), "
                f"{arrow}, style=Styles.DarkBold)"
            )
        elif len(pts) > 2:
            lines.append(f"lines([{pts_str}], {arrow}, style=Styles.DarkBold)")

        if edge.label:
            mid_idx = len(pts) // 2
            if len(pts) % 2 == 0:
                p1 = pts[mid_idx - 1]
                p2 = pts[mid_idx]
                lx = (p1[0] + p2[0]) / 2.0
                ly = (p1[1] + p2[1]) / 2.0 + 2.0
            else:
                lx = pts[mid_idx][0]
                ly = pts[mid_idx][1] + 2.0
            lines.append(f'text(({lx:.1f}, {ly:.1f}), "{edge.label}", style=Styles.DarkBold)')
    return lines


def _format_coordinates_code(nodes: dict[str, NodeLayout]) -> list[str]:
    """Format semantic coordinate variables for nodes."""
    if not nodes:
        return []
    lines: list[str] = [
        "",
        "# " + "=" * 77,
        "# Node Coordinates",
        "# " + "=" * 77,
    ]
    for node in nodes.values():
        var_name = f"{node.id}_xy"
        lines.append(f"{var_name} = ({node.x:.1f}, {node.y:.1f})")
    return lines


def _format_nodes_code(nodes: dict[str, NodeLayout]) -> list[str]:
    """Format nodes section."""
    if not nodes:
        return []
    lines: list[str] = [
        "",
        "# " + "=" * 77,
        "# 3. Nodes (Z-Order Layer 3)",
        "# " + "=" * 77,
    ]
    for node in nodes.values():
        var_name = f"{node.id}_xy"
        lbl = f'text="{node.label}"'
        if node.shape == "circle":
            r = node.width / 2.0
            lines.append(f"circle({var_name}, radius={r:.1f}, {lbl}, style=Styles.PrimaryFlat)")
        elif node.shape == "rounded_rectangle":
            lines.append(
                f"rectangle({var_name}, width={node.width:.1f}, height={node.height:.1f}, "
                f"r=2.0, {lbl}, style=Styles.PrimaryFlat)"
            )
        else:
            lines.append(
                f"rectangle({var_name}, width={node.width:.1f}, height={node.height:.1f}, "
                f"{lbl}, style=Styles.PrimaryFlat)"
            )
    return lines


def generate_code(layout: GraphLayout) -> str:
    """Generate executable Drawlib Python script representing the layout geometry.

    Args:
        layout: Complete geometrical graph layout object.

    Returns:
        Formatted Python source code string.
    """
    code_lines: list[str] = []
    code_lines.extend(_format_header_code(layout.width, layout.height))
    code_lines.extend(_format_coordinates_code(layout.nodes))
    code_lines.extend(_format_clusters_code(layout.clusters))
    code_lines.extend(_format_edges_code(layout.edges))
    code_lines.extend(_format_nodes_code(layout.nodes))
    code_lines.extend(["", "save()", ""])
    return "\n".join(code_lines)
