"""
This type stub file was generated by pyright.
"""

import drawlib.v0_1.private.util

"""Canvas related utilities."""
@drawlib.v0_1.private.util.error_handler
def initialize() -> None:
    """Initialize the drawing environment by applying the official theme and clearing the image cache.

    This function performs the following steps:
    1. Clears the drawing canvas.
    2. Applies the official "default" theme using the `dtheme` module.
    3. Deletes all images in the `Dimage` cache.

    Returns:
        None

    """
    ...

