name: unit test
run-name: os=${{ github.event.inputs.os }}, python=${{ github.event.inputs.python_version }}, from=${{ github.event.inputs.install_from }}, branch=${{ github.event.inputs.branch }}, version=${{ github.event.inputs.lib_version }}

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
          
      python_version:
        description: 'Python version'
        required: true
        default: '3.9'
        type: choice
        options:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          
      install_from:
        description: 'Where you get the library'
        required: true
        default: 'github'
        type: choice
        options:
          - 'github'
          - 'pypi'
          - 'testpypi'
          
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'main'
        type: string
        
      lib_version:
        description: 'drawlib version. Ignored when install_from=github'
        required: true
        default: 'latest'
        type: string
        

jobs:
  build:

    runs-on: ${{ github.event.inputs.os }}

    steps:
    - name: Display Inputs
      run: |
        echo "Running on OS: ${{ github.event.inputs.os }}"
        echo "Python version: ${{ github.event.inputs.python_version }}"
        echo "Installing from: ${{ github.event.inputs.install_from }}"
        echo "Library version: ${{ github.event.inputs.lib_version }}"
        echo "Branch: ${{ github.event.inputs.branch }}"
        
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ github.event.inputs.python_version }}

    - name: Install dependencies
      run: |
        if [ "${{ github.event.inputs.install_from }}" == "github" ]; then
            curl -sSL https://install.python-poetry.org | python -
            echo "$HOME/.local/bin" >> $GITHUB_PATH  # Add poetry to PATH for the current session
            poetry install

        else
            rm -rf ./drawlib
            pip install pytest pytest-cov
          
            if [ "${{ github.event.inputs.install_from }}" == "pypi" ]; then
                if [ "${{ github.event.inputs.lib_version }}" == "latest" ]; then
                    pip install drawlib
                else
                    pip install drawlib=="${{ github.event.inputs.lib_version }}"
                fi
            
            elif [ "${{ github.event.inputs.install_from }}" == "testpypi" ]; then
                if [ "${{ github.event.inputs.lib_version }}" == "latest" ]; then
                    pip install --index-url https://test.pypi.org/simple/ drawlib
                else
                    pip install --index-url https://test.pypi.org/simple/ drawlib=="${{ github.event.inputs.lib_version }}"
                fi
            else
                echo install_from is not supported "${{ github.event.inputs.install_from }}"
                exit 1
            fi
        fi

    - name: Run tests
      run: |
        if [ "${{ github.event.inputs.install_from }}" == "github" ]; then
            poetry run pytest -s --cov=drawlib tests/
        else
            pytest -s --cov=drawlib tests/
        fi
