name: unit tests

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Runs on OS'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'main'
        type: string
      python_version:
        description: 'Python version to use'
        required: true
        default: '3.9'
        type: choice
        options:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'

jobs:
  build:

    runs-on: ${{ github.event.inputs.os }}

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ github.event.inputs.python_version }}

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.local/bin" >> $GITHUB_PATH  # Add poetry to PATH for the current session
        poetry install

    - name: Run tests
      run: |
        poetry run pytest -s --cov=drawlib tests/
